// TODO: should import Application

import { Application } from "@/types/Application";

// Mock data - only individual applications
export const mockApplications: Application[] = [
  {
    id: 'app-1',
    applicantName: 'John Doe',
    email: 'joed@example.com',
    submittedDate: '2025-07-18T14:30:00',
    lastUpdated: '2025-07-20T09:15:00',
    status: 'admitted',
    school: 'Massachusetts Institute of Technology',
    levelOfStudy: 'Undergraduate - Junior',
    countryOfResidence: 'United States',
    linkedinUrl: 'https://linkedin.com/in/michaelchen',
    dietaryVegetarian: false,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: false,
    tshirtSize: 'M',
    majorFieldOfStudy: 'Computer Science',
    gender: 'Male',
    pronouns: 'he/him',
    raceEthnicity: 'Asian',
    sexualOrientation: 'Prefer not to say'
  },
  {
    id: 'app-2',
    applicantName: 'Jane Doe',
    email: 'jade@example.com',
    submittedDate: '2025-07-22T09:15:00',
    lastUpdated: '2025-07-22T09:15:00',
    status: 'pending',
    school: 'Stanford University',
    levelOfStudy: 'Graduate - Masters',
    countryOfResidence: 'United States',
    linkedinUrl: 'https://linkedin.com/in/sarahjohnson',
    dietaryVegetarian: true,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: false,
    tshirtSize: 'S',
    majorFieldOfStudy: 'Artificial Intelligence',
    gender: 'Female',
    pronouns: 'she/her',
    raceEthnicity: 'White',
    sexualOrientation: 'Heterosexual'
  },
  {
    id: 'app-3',
    applicantName: 'Joe Doe',
    email: 'joe.doe@example.com',
    submittedDate: '2025-07-28T16:45:00',
    lastUpdated: '2025-07-30T10:20:00',
    status: 'admitted',
    school: 'University of California, Berkeley',
    levelOfStudy: 'Undergraduate - Senior',
    countryOfResidence: 'United States',
    linkedinUrl: 'https://linkedin.com/in/jamalwilliams',
    dietaryVegetarian: false,
    dietaryVegan: true,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: false,
    tshirtSize: 'L',
    majorFieldOfStudy: 'Environmental Engineering',
    gender: 'Male',
    pronouns: 'he/him',
    raceEthnicity: 'Black or African American',
    sexualOrientation: 'Prefer not to say'
  },
  {
    id: 'app-4',
    applicantName: 'Joe Momma',
    email: 'joes.momp@example.com',
    submittedDate: '2025-08-01T11:20:00',
    lastUpdated: '2025-08-01T11:20:00',
    status: 'pending',
    school: 'Cool School',
    levelOfStudy: 'Undergraduate - Sophomore',
    countryOfResidence: 'Canada',
    linkedinUrl: 'https://linkedin.com/in/priyapatel',
    dietaryVegetarian: true,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: true,
    tshirtSize: 'XS',
    majorFieldOfStudy: 'Computer Engineering',
    gender: 'Female',
    pronouns: 'she/her',
    raceEthnicity: 'Asian',
    sexualOrientation: 'Prefer not to say'
  },
  {
    id: 'app-5',
    applicantName: 'Alex Rivera',
    email: 'alex.r@example.com',
    submittedDate: '2025-08-03T13:05:00',
    lastUpdated: '2025-08-03T13:05:00',
    status: 'waitlisted',
    school: 'Cool School',
    levelOfStudy: 'Undergraduate - Junior',
    countryOfResidence: 'United States',
    linkedinUrl: 'https://linkedin.com/in/alexrivera',
    dietaryVegetarian: false,
    dietaryVegan: false,
    dietaryCeliacDisease: true,
    dietaryKosher: false,
    dietaryHalal: false,
    tshirtSize: 'M',
    majorFieldOfStudy: 'Data Science',
    gender: 'Non-binary',
    pronouns: 'they/them',
    raceEthnicity: 'Hispanic or Latino',
    sexualOrientation: 'Bisexual'
  },
  {
    id: 'app-6',
    applicantName: 'Mark Zuckerberg',
    email: 'mberg@example.com',
    submittedDate: '2025-08-05T10:00:00',
    lastUpdated: '2025-08-05T10:00:00',
    status: 'pending',
    school: 'Cool School',
    levelOfStudy: 'Undergraduate - Freshman',
    countryOfResidence: 'Canada',
    linkedinUrl: 'https://linkedin.com/in/emilyzhang',
    dietaryVegetarian: false,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: false,
    tshirtSize: 'S',
    majorFieldOfStudy: 'Software Engineering',
    gender: 'Female',
    pronouns: 'she/her',
    raceEthnicity: 'Asian',
    sexualOrientation: 'Prefer not to say'
  },
  {
    id: 'app-7',
    applicantName: 'Manny Pacquiao',
    email: 'mp.ph@example.com',
    submittedDate: '2025-08-06T15:30:00',
    lastUpdated: '2025-08-06T15:30:00',
    status: 'rejected',
    school: 'Cool School',
    levelOfStudy: 'Graduate - PhD',
    countryOfResidence: 'Israel',
    linkedinUrl: 'https://linkedin.com/in/davidcohen',
    dietaryVegetarian: false,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: true,
    dietaryHalal: false,
    tshirtSize: 'L',
    majorFieldOfStudy: 'Cryptography',
    gender: 'Male',
    pronouns: 'he/him',
    raceEthnicity: 'White',
    sexualOrientation: 'Heterosexual'
  },
  {
    id: 'app-8',
    applicantName: 'John Doe the 2nd',
    email: 'jdt2.m@example.com',
    submittedDate: '2025-08-07T08:45:00',
    lastUpdated: '2025-08-07T08:45:00',
    status: 'waitlisted',
    school: 'Cool School',
    levelOfStudy: 'Graduate - Masters',
    countryOfResidence: 'United Kingdom',
    linkedinUrl: 'https://linkedin.com/in/aishamohammed',
    dietaryVegetarian: false,
    dietaryVegan: false,
    dietaryCeliacDisease: false,
    dietaryKosher: false,
    dietaryHalal: true,
    tshirtSize: 'M',
    majorFieldOfStudy: 'Machine Learning',
    gender: 'Female',
    pronouns: 'she/her',
    raceEthnicity: 'Black or African American',
    sexualOrientation: 'Prefer not to say'
  }
];
